development:
  adapter: postgresql
  encoding: unicode
  database: {{database_name}}
  pool: 5
  username: {{username}}
  password: {{password}}

test:
  adapter: postgresql
  encoding: unicode
  database: {{test_database_name}}
  pool: 5
  username: {{username}}
  password: {{password}}
